# Below configuration, we have to pass service instance id in the parameter
#spring:
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true   #Lowercase service id also allowed

spring:
  cloud:
    gateway:
      routes:
        - id: CUSTOMERSERVICE
          uri: lb://CUSTOMERSERVICE
          predicates:
            - Path=/customer/**
        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotel/**, /staff/** #Multiple controllers
        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/rating/**

eureka:
  instance:
    prefer-ip-address: true
